services: 
  migrations: 
    image: ${DOCKER_REGISTRY-}taskmanagerapi
    build: 
      context: .
      dockerfile: Dockerfile
      target: migrations
    ports: 
      - "8081:8080"
    depends_on: 
      - db
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

  db: 
    container_name: db
    image: postgres
    environment: 
      ACCEPT_EULA: Y
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: senha
      POSTGRES_DB: TaskManagerAPI
    ports: 
      - "5432:5432"